services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.4.0@sha256:545fb8af4287ad027e4f7eb8a0464fa2e21f157e88fda3d7a514ba1e6d3a86b0
    container_name: mealie
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.mealie.loadbalancer.server.port=9000
      - show.external=true
    env_file:
      - mealie.env
    volumes:
      - ./data:/app/data/

networks:
  default:
    external: true
    name: ctr-network
