services:
  nginx:
    image: nginx:1.29.4-alpine-slim@sha256:fc0cff8d49db19250104d2fba8bd1ee3fc2a09ed8163de582804e5d137df7821
    container_name: nginx
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./jellyfin.conf:/etc/nginx/conf.d/jellyfin.conf:ro
      - ./etc_letsencrypt:/etc/letsencrypt:ro
    restart: 'unless-stopped'
    networks:
      default:
        ipv4_address: 172.18.128.12
networks:
  default:
    external: true
    name: ctr-network