services:
  nginx:
    image: nginx:1.29.5-alpine-slim@sha256:a716a2895ddba4fa7fca05e1003579f76d3d304932781426a211bc72b51f0c4e
    container_name: nginx
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./jellyfin.conf:/etc/nginx/conf.d/jellyfin.conf:ro
      - ./etc_letsencrypt:/etc/letsencrypt:ro
    restart: 'unless-stopped'
    networks:
      default:
        ipv4_address: 172.18.128.12
networks:
  default:
    external: true
    name: ctr-network